global:
  slack_api_url: 'https://hooks.slack.com/services/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'

route:
  receiver: 'slack-notifications'

receivers:
- name: 'slack-notifications'
  slack_configs:
  - channel: '#aleksei_lakhno'
