version: '3.3'
services:
  mongo_db:
    image: mongo:${MONGO_VERSION}
    volumes:
      - post_db:/data/db
    networks:
      back-net:
        aliases:
          - post_db
          - comment_db
  ui:
    image: ${USER_NAME}/ui:${UI_VERSION}
    ports:
      - ${UI_PORT}:9292/tcp
    networks:
      - front-net
  post:
    image: ${USER_NAME}/post:${POST_VERSION}
    networks:
      - back-net
      - front-net
  comment:
    image: ${USER_NAME}/comment:${COMMENT_VERSION}
    networks:
      - back-net
      - front-net

volumes:
  post_db:

networks:
  back-net:
  front-net:
